"""empty message

Revision ID: e3da170e2e02
Revises: efa2bc20b4fc
Create Date: 2018-04-15 06:24:35.257240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3da170e2e02'
down_revision = 'efa2bc20b4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geolocation')
    # ### end Alembic commands ###
